---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
   name: volume-ntnx-nfs
   annotations:
        storageclass.kubernetes.io/is-default-class: "false"
   labels:
    app.kubernetes.io/name: ntnx-plugin
    app.kubernetes.io/part-of: csi-ntnx-plugin
provisioner: com.nutanix.csi
parameters:     
   nfsServer: <NTNX-IP>
   nfsPath: <NTNX-files-export>
reclaimPolicy: Retain